package Vistas;

import entidades.*;
import static java.lang.Float.parseFloat;
import modelo.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class VistaDetallePedido extends javax.swing.JInternalFrame {

    private PedidoData pedidoData;
    private Conexion conexion;
        
    public VistaDetallePedido() {
        initComponents();
        conexion = new Conexion();
        pedidoData = new PedidoData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jl_Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_IdPedido = new javax.swing.JTextField();
        jtf_CantidadDeCajas = new javax.swing.JTextField();
        jtf_EstrellasTotales = new javax.swing.JTextField();
        jb_Limpiar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jb_Buscar = new javax.swing.JButton();
        jtf_ImporteTotal = new javax.swing.JTextField();
        jl_ImporteTotal = new javax.swing.JLabel();
        jl_FechaEntrega = new javax.swing.JLabel();
        jtf_FechaEntrega = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("AIVON");

        jl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 255));
        jl_Titulo.setText("-Detalle de Pedido-");

        jLabel2.setText("Estrellas Totales");

        jLabel3.setText("Cantidad de Cajas");

        jLabel4.setText("Id Pedido");

        jtf_IdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_IdPedidoActionPerformed(evt);
            }
        });

        jb_Limpiar.setText("LIMPIAR");
        jb_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimpiarActionPerformed(evt);
            }
        });

        jButton5.setText("jButton3");

        jb_Buscar.setText("Buscar");
        jb_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarActionPerformed(evt);
            }
        });

        jtf_ImporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ImporteTotalActionPerformed(evt);
            }
        });

        jl_ImporteTotal.setText("Importe Total");

        jl_FechaEntrega.setText("Fecha Entrega");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_ImporteTotal)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jl_FechaEntrega))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtf_IdPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(jtf_CantidadDeCajas)
                                .addComponent(jtf_EstrellasTotales, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_ImporteTotal, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtf_FechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(429, Short.MAX_VALUE)
                    .addComponent(jButton5)
                    .addGap(61, 61, 61)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtf_IdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtf_CantidadDeCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Buscar))
                        .addGap(18, 18, 18)
                        .addComponent(jb_Limpiar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtf_EstrellasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_ImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_ImporteTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_FechaEntrega)
                    .addComponent(jtf_FechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_IdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_IdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_IdPedidoActionPerformed

    private void jb_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarActionPerformed
        Pedido p = new Pedido();
        p = pedidoData.buscarPedido(Integer.parseInt(jtf_IdPedido.getText()));
        if (p != null)
        {
            jtf_IdPedido.setText(p.getIdPedido() + "");
            jtf_CantidadDeCajas.setText(p.getCantCajas() + "");
            jtf_EstrellasTotales.setText(p.getEstrellaXpedido() + "");
            jtf_ImporteTotal.setText(p.getImporteTotal() + "");
            jtf_FechaEntrega.setText(p.getFechaEntrega().toString());
        }
    }//GEN-LAST:event_jb_BuscarActionPerformed

    private void jtf_ImporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ImporteTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ImporteTotalActionPerformed

    private void jb_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimpiarActionPerformed
        jtf_IdPedido.setText("");
        jtf_CantidadDeCajas.setText("");
        jtf_EstrellasTotales.setText("");
        jtf_FechaEntrega.setText("");
        jtf_ImporteTotal.setText("");
    }//GEN-LAST:event_jb_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Limpiar;
    private javax.swing.JLabel jl_FechaEntrega;
    private javax.swing.JLabel jl_ImporteTotal;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JTextField jtf_CantidadDeCajas;
    private javax.swing.JTextField jtf_EstrellasTotales;
    private javax.swing.JTextField jtf_FechaEntrega;
    private javax.swing.JTextField jtf_IdPedido;
    private javax.swing.JTextField jtf_ImporteTotal;
    // End of variables declaration//GEN-END:variables
}
