/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class VistaPedido extends javax.swing.JFrame {

    /**
     * Creates new form VistaPedido
     */
    public VistaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jif_Pedido = new javax.swing.JInternalFrame();
        jl_Titulo = new javax.swing.JLabel();
        jl_IdPedido = new javax.swing.JLabel();
        jl_IdRevendedor = new javax.swing.JLabel();
        jl_IdCampaña = new javax.swing.JLabel();
        jl_FechaIngreso = new javax.swing.JLabel();
        jl_FechaPago = new javax.swing.JLabel();
        jl_FechaEntrga = new javax.swing.JLabel();
        jl_CantidadDeCajas = new javax.swing.JLabel();
        jl_EstrellaPorPedido = new javax.swing.JLabel();
        jl_EstadoPedido = new javax.swing.JLabel();
        jtf_EstadoPedido = new javax.swing.JTextField();
        jtf_EstrellaPorPedido = new javax.swing.JTextField();
        jtf_CantidadDeCajas = new javax.swing.JTextField();
        jtf_FechaPago = new javax.swing.JTextField();
        jtf_FechaEntrega = new javax.swing.JTextField();
        jtf_FechaIngreso = new javax.swing.JTextField();
        jtf_IdCampaña = new javax.swing.JTextField();
        jtf_IdRevendedor = new javax.swing.JTextField();
        jtf_IdPedido = new javax.swing.JTextField();
        jb_Guardar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jb_Buscar = new javax.swing.JButton();
        jb_Actualizar = new javax.swing.JButton();
        jb_ListarPedido = new javax.swing.JButton();
        jb_PedidosPorCampaña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jif_Pedido.setClosable(true);
        jif_Pedido.setIconifiable(true);
        jif_Pedido.setMaximizable(true);
        jif_Pedido.setResizable(true);
        jif_Pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jif_Pedido.setVisible(true);

        jl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 255));
        jl_Titulo.setText("-Pedido-");

        jl_IdPedido.setText("Id Pedido");

        jl_IdRevendedor.setText("Id Revendedor");

        jl_IdCampaña.setText("Id Campaña");

        jl_FechaIngreso.setText("Fecha De Ingreso");

        jl_FechaPago.setText("Fecha De Pago");

        jl_FechaEntrga.setText("Fecha De Entrega");

        jl_CantidadDeCajas.setText("Cantidad de Cajas");

        jl_EstrellaPorPedido.setText("Estrella Por Pedido");

        jl_EstadoPedido.setText("Estado Pedido");

        jb_Guardar.setText("Guardar");

        jb_Eliminar.setText("Eliminar");

        jb_Buscar.setText("Buscar");

        jb_Actualizar.setText("Actualizar");

        jb_ListarPedido.setText("Lista Pedidos");

        jb_PedidosPorCampaña.setText("Pedidos Por Campaña ");

        javax.swing.GroupLayout jif_PedidoLayout = new javax.swing.GroupLayout(jif_Pedido.getContentPane());
        jif_Pedido.getContentPane().setLayout(jif_PedidoLayout);
        jif_PedidoLayout.setHorizontalGroup(
            jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jif_PedidoLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jl_Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jif_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jif_PedidoLayout.createSequentialGroup()
                        .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_IdRevendedor)
                            .addComponent(jl_IdPedido))
                        .addGap(72, 72, 72))
                    .addGroup(jif_PedidoLayout.createSequentialGroup()
                        .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_IdCampaña)
                            .addComponent(jl_FechaIngreso)
                            .addComponent(jl_FechaEntrga)
                            .addComponent(jl_FechaPago)
                            .addComponent(jl_CantidadDeCajas)
                            .addComponent(jl_EstrellaPorPedido)
                            .addComponent(jl_EstadoPedido))
                        .addGap(55, 55, 55)))
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_IdPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jtf_IdRevendedor)
                    .addComponent(jtf_IdCampaña)
                    .addComponent(jtf_FechaIngreso)
                    .addComponent(jtf_FechaPago)
                    .addComponent(jtf_FechaEntrega)
                    .addComponent(jtf_CantidadDeCajas)
                    .addComponent(jtf_EstrellaPorPedido)
                    .addComponent(jtf_EstadoPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_PedidosPorCampaña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_ListarPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jif_PedidoLayout.setVerticalGroup(
            jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jif_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Titulo)
                .addGap(36, 36, 36)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_IdPedido)
                    .addComponent(jtf_IdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_IdRevendedor)
                    .addComponent(jtf_IdRevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_IdCampaña)
                    .addComponent(jtf_IdCampaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaIngreso)
                    .addComponent(jtf_FechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaEntrga)
                    .addComponent(jtf_FechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ListarPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaPago)
                    .addComponent(jtf_FechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_PedidosPorCampaña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_CantidadDeCajas)
                    .addComponent(jtf_CantidadDeCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_EstrellaPorPedido)
                    .addComponent(jtf_EstrellaPorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jif_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_EstadoPedido)
                    .addComponent(jtf_EstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jif_Pedido))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jif_Pedido)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Actualizar;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_Guardar;
    private javax.swing.JButton jb_ListarPedido;
    private javax.swing.JButton jb_PedidosPorCampaña;
    private javax.swing.JInternalFrame jif_Pedido;
    private javax.swing.JLabel jl_CantidadDeCajas;
    private javax.swing.JLabel jl_EstadoPedido;
    private javax.swing.JLabel jl_EstrellaPorPedido;
    private javax.swing.JLabel jl_FechaEntrga;
    private javax.swing.JLabel jl_FechaIngreso;
    private javax.swing.JLabel jl_FechaPago;
    private javax.swing.JLabel jl_IdCampaña;
    private javax.swing.JLabel jl_IdPedido;
    private javax.swing.JLabel jl_IdRevendedor;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JTextField jtf_CantidadDeCajas;
    private javax.swing.JTextField jtf_EstadoPedido;
    private javax.swing.JTextField jtf_EstrellaPorPedido;
    private javax.swing.JTextField jtf_FechaEntrega;
    private javax.swing.JTextField jtf_FechaIngreso;
    private javax.swing.JTextField jtf_FechaPago;
    private javax.swing.JTextField jtf_IdCampaña;
    private javax.swing.JTextField jtf_IdPedido;
    private javax.swing.JTextField jtf_IdRevendedor;
    // End of variables declaration//GEN-END:variables
}
