/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class VistaCampaña extends javax.swing.JFrame {

    /**
     * Creates new form VistaCampaña
     */
    public VistaCampaña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        jl_IdCampaña = new javax.swing.JLabel();
        jl_FechaInicio = new javax.swing.JLabel();
        jl_FechaFinal = new javax.swing.JLabel();
        jl_MontoMinimo = new javax.swing.JLabel();
        jl_MohtoMaximo = new javax.swing.JLabel();
        jl_EstrellaPorCampaña = new javax.swing.JLabel();
        jtf_IdCampaña = new javax.swing.JTextField();
        jtf_FechaInicio = new javax.swing.JTextField();
        jtf_FechaFinal = new javax.swing.JTextField();
        jtf_MontoMinimo = new javax.swing.JTextField();
        jtf_MontoMaximo = new javax.swing.JTextField();
        jtf_EstrellaPorCampaña = new javax.swing.JTextField();
        jb_Buscar = new javax.swing.JButton();
        jb_Cargar = new javax.swing.JButton();
        jb_Actualizar = new javax.swing.JButton();
        jb_Limpiar = new javax.swing.JButton();
        jb_Borra = new javax.swing.JButton();
        jb_Listar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 255));
        jl_Titulo.setText("-Camapaña-");

        jl_IdCampaña.setText("Id Campaña");

        jl_FechaInicio.setText("Fecha Inicio");

        jl_FechaFinal.setText("Fecha Final ");

        jl_MontoMinimo.setText("Monto Minimo");

        jl_MohtoMaximo.setText("Monto Maximo");

        jl_EstrellaPorCampaña.setText("Estrella Por Campaña");

        jtf_FechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_FechaFinalActionPerformed(evt);
            }
        });

        jb_Buscar.setText("Buscar");

        jb_Cargar.setText("Cargar");

        jb_Actualizar.setText("Actualizar");

        jb_Limpiar.setText("Limpiar");

        jb_Borra.setText("Borrar");

        jb_Listar.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_IdCampaña)
                    .addComponent(jl_FechaInicio)
                    .addComponent(jl_FechaFinal)
                    .addComponent(jl_MontoMinimo)
                    .addComponent(jl_MohtoMaximo)
                    .addComponent(jl_EstrellaPorCampaña))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_IdCampaña)
                    .addComponent(jtf_FechaInicio)
                    .addComponent(jtf_FechaFinal)
                    .addComponent(jtf_MontoMinimo)
                    .addComponent(jtf_MontoMaximo)
                    .addComponent(jtf_EstrellaPorCampaña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_Buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_Borra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_Cargar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_Listar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_Actualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_Limpiar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Titulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_IdCampaña)
                    .addComponent(jtf_IdCampaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaInicio)
                    .addComponent(jtf_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Borra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_FechaFinal)
                    .addComponent(jtf_FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Actualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_MontoMinimo)
                    .addComponent(jtf_MontoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Cargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_MohtoMaximo)
                    .addComponent(jtf_MontoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Listar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_EstrellaPorCampaña)
                    .addComponent(jtf_EstrellaPorCampaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Limpiar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_FechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_FechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_FechaFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCampaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCampaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCampaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCampaña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCampaña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Actualizar;
    private javax.swing.JButton jb_Borra;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Cargar;
    private javax.swing.JButton jb_Limpiar;
    private javax.swing.JButton jb_Listar;
    private javax.swing.JLabel jl_EstrellaPorCampaña;
    private javax.swing.JLabel jl_FechaFinal;
    private javax.swing.JLabel jl_FechaInicio;
    private javax.swing.JLabel jl_IdCampaña;
    private javax.swing.JLabel jl_MohtoMaximo;
    private javax.swing.JLabel jl_MontoMinimo;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JTextField jtf_EstrellaPorCampaña;
    private javax.swing.JTextField jtf_FechaFinal;
    private javax.swing.JTextField jtf_FechaInicio;
    private javax.swing.JTextField jtf_IdCampaña;
    private javax.swing.JTextField jtf_MontoMaximo;
    private javax.swing.JTextField jtf_MontoMinimo;
    // End of variables declaration//GEN-END:variables
}
